---

antora:
  name: modules
  dir: www
  modules:
    - name: 01-playbook-inventory
      label: Meet the Coding Assistant
      solveButton: true
    - name: 02-generate-comprehensive-playbook
      label: Generate a Comprehensive Playbook
      solveButton: true
    - name: 03-understand-the-playbook
      label: Understand Your Playbook
      solveButton: false
    - name: 04-playbook-run-it
      label: Run and Verify
      solveButton: true
    - name: 05-generate-roles
      label: Convert to a Role
      solveButton: true
    - name: 06-wrap-up
      label: Wrap-Up and Next Steps
      solveButton: false

tabs:
  - name: VS Code
    url: https://vscode-${guid}.${domain}/?folder=/home/rhel/ansible-files
    external: false
  - name: node1 Web
    url: https://node1-http-${guid}.${domain}/
    external: false
  - name: node2 Web
    url: https://node2-http-${guid}.${domain}/
    external: false
