---

antora:
  name: modules
  dir: www
  modules:
    - name: 01-playbook-inventory
      label: Meet Ansible Lightspeed
      solveButton: true
    - name: 02-generate-comprehensive-playbook
      label: Generate a Comprehensive Playbook
      solveButton: true
    - name: 03-playbook-run-it
      label: Run and Verify
      solveButton: true
    - name: 04-wrap-up
      label: Wrap-Up and Next Steps
      solveButton: false

tabs:
  - name: VS Code
    url: https://vscode-${guid}.${domain}/
    external: false
  - name: Control
    url: /wetty
    external: false
  - name: Node01
    url: /wetty_node01
    external: false
  - name: Node02
    url: /wetty_node02
    external: false
  - name: Node03
    url: /wetty_node03
    external: false
