---
- name: Setup nodes for comprehensive playbook execution
  hosts: nodes
  become: true
  tasks:
    - name: Install packages needed for httpd
      ansible.builtin.dnf:
        name: cups-filesystem
        state: present

    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled

    - name: Ensure firewalld allows HTTP traffic
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
