#!/bin/bash
# Auto-generated by Lab Foundry validate-lab
# Run after provisioning to verify lab health for zt-writing-your-first-playbook

WEBHOOK_URL="${HEALTH_WEBHOOK_URL:-}"
LAB_NAME="zt-writing-your-first-playbook"
GUID="${GUID:-unknown}"
DOMAIN="${DOMAIN:-example.com}"
RESULTS=()
FAILURES=0

check_http() {
    local name=$1
    local url=$2
    local expected_code=${3:-200}
    local code
    code=$(curl -sk -o /dev/null -w '%{http_code}' --connect-timeout 10 "$url" 2>/dev/null)
    if [ "$code" = "$expected_code" ]; then
        RESULTS+=("PASS: $name ($url) - HTTP $code")
    else
        RESULTS+=("FAIL: $name ($url) - expected $expected_code, got $code")
        ((FAILURES++))
    fi
}

check_port() {
    local name=$1
    local host=$2
    local port=$3
    if timeout 5 bash -c "echo >/dev/tcp/$host/$port" 2>/dev/null; then
        RESULTS+=("PASS: $name ($host:$port) - port open")
    else
        RESULTS+=("FAIL: $name ($host:$port) - port closed or unreachable")
        ((FAILURES++))
    fi
}

# SSH reachability checks (internal lab network)
check_port "control SSH" "control" 22
check_port "node1 SSH"   "node1"   22
check_port "node2 SSH"   "node2"   22
check_port "node3 SSH"   "node3"   22

# VS Code (code-server) service — runs on control VM, exposed via vscode-8080 route
check_http "VS Code (code-server)" "https://vscode-${GUID}.${DOMAIN}" 200

# code-server port on control VM (internal)
check_port "code-server on control" "control" 8080

# LiteLLM proxy on control VM (Ansible Lightspeed AI backend)
check_port "LiteLLM proxy on control" "control" 4000

report_results() {
    local status="SUCCESS"
    [ "$FAILURES" -gt 0 ] && status="FAILED ($FAILURES failures)"

    local report
    report="Lab Health Report: $LAB_NAME (GUID: $GUID)\nStatus: $status\n"
    for r in "${RESULTS[@]}"; do
        report+="  $r\n"
    done

    echo -e "$report"

    if [ -n "$WEBHOOK_URL" ]; then
        curl -s -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"$report\", \"lab\": \"$LAB_NAME\", \"guid\": \"$GUID\", \"status\": \"$status\", \"failures\": $FAILURES}" \
            2>/dev/null || true
    fi
}

report_results
exit $FAILURES
